#before_script:
#  - ssh-keyscan -t rsa,dsa,ecdsa github.com > /etc/ssh/ssh_known_hosts
stages:
  - mirror
  
variables:
  MIRROR_REPOSITORY: "git@github.com:h44z/atestproject.git"
  MIRROR_BRANCH: "master"

mirror-github:
  stage: mirror
  cache: {}
  script:
    # run ssh-agent
    #- eval $(ssh-agent -s)
    # add appropriate private key to the agent store
    #- ssh-add <(echo "$MIRROR_KEY")
    # set known hosts list
    # WARNING: use only in docker container, if you use it with shell you will
    # overwrite your user's ssh config
    #- mkdir -p ~/.ssh
    #- cp deploy/known_hosts ~/.ssh/known_hosts
    # Do a mirror clone of the repository
    - git clone --mirror $CI_REPOSITORY_URL
    # Mirror push it to the destination
    - cd $CI_PROJECT_NAME.git
    - git push --mirror $MIRROR_REPOSITORY
    # Cleanup
    - cd ..; rm -rf $CI_PROJECT_NAME.git

#mirror-master:
#  stage: deploy
#  only:
#    - master
#  script:
#    - git remote add --mirror=push github $UPSTREAM_REPOSITORY || true
#    - git push --quiet github
#    - git fetch upstream
#    - git push --progress upstream HEAD:$UPSTREAM_BRANCH

#mirror-tags:
#  stage: deploy
#  only:
#    - tags
#  script:
#    - git remote add upstream $UPSTREAM_REPOSITORY || true
#    - git fetch upstream
#    - git push --progress --tags upstream